// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: hotmethod.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HotmethodClient is the client API for Hotmethod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotmethodClient interface {
	NotifyResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateTaskStatus(ctx context.Context, in *TaskStatusUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type hotmethodClient struct {
	cc grpc.ClientConnInterface
}

func NewHotmethodClient(cc grpc.ClientConnInterface) HotmethodClient {
	return &hotmethodClient{cc}
}

func (c *hotmethodClient) NotifyResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/drop.Hotmethod/NotifyResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotmethodClient) UpdateTaskStatus(ctx context.Context, in *TaskStatusUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/drop.Hotmethod/UpdateTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotmethodServer is the server API for Hotmethod service.
// All implementations must embed UnimplementedHotmethodServer
// for forward compatibility
type HotmethodServer interface {
	NotifyResult(context.Context, *TaskResult) (*emptypb.Empty, error)
	UpdateTaskStatus(context.Context, *TaskStatusUpdate) (*emptypb.Empty, error)
	mustEmbedUnimplementedHotmethodServer()
}

// UnimplementedHotmethodServer must be embedded to have forward compatible implementations.
type UnimplementedHotmethodServer struct {
}

func (UnimplementedHotmethodServer) NotifyResult(context.Context, *TaskResult) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyResult not implemented")
}
func (UnimplementedHotmethodServer) UpdateTaskStatus(context.Context, *TaskStatusUpdate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}
func (UnimplementedHotmethodServer) mustEmbedUnimplementedHotmethodServer() {}

// UnsafeHotmethodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotmethodServer will
// result in compilation errors.
type UnsafeHotmethodServer interface {
	mustEmbedUnimplementedHotmethodServer()
}

func RegisterHotmethodServer(s grpc.ServiceRegistrar, srv HotmethodServer) {
	s.RegisterService(&Hotmethod_ServiceDesc, srv)
}

func _Hotmethod_NotifyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotmethodServer).NotifyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drop.Hotmethod/NotifyResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotmethodServer).NotifyResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hotmethod_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotmethodServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drop.Hotmethod/UpdateTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotmethodServer).UpdateTaskStatus(ctx, req.(*TaskStatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// Hotmethod_ServiceDesc is the grpc.ServiceDesc for Hotmethod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hotmethod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drop.Hotmethod",
	HandlerType: (*HotmethodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyResult",
			Handler:    _Hotmethod_NotifyResult_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _Hotmethod_UpdateTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotmethod.proto",
}
